# Generated by Django 4.1.7 on 2023-03-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Banks',
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('ifsc', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('banks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.publicbank')),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'db_table': 'branches',
            },
        ),
    ]
